import { Transaction, Wallet, Budget, Investment, Debt, EXPENSE_CATEGORIES, INCOME_CATEGORIES, WALLET_LABELS } from "@/types";

export function formatCurrency(amount: number, currency: string = "IDR"): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export function exportToCSV(
  data: Transaction[],
  wallets: Wallet[],
  filename: string = "transactions"
): void {
  const walletMap = new Map(wallets.map(w => [w.id, w.name]));
  
  const headers = ["Tanggal", "Tipe", "Kategori", "Jumlah", "Dompet", "Catatan"];
  const rows = data.map(t => [
    t.date,
    t.type === "income" ? "Pemasukan" : "Pengeluaran",
    t.category,
    t.amount.toString(),
    walletMap.get(t.walletId || "") || "-",
    t.note || "-"
  ]);
  
  const csvContent = [headers, ...rows]
    .map(row => row.map(cell => `"${cell}"`).join(","))
    .join("\n");
  
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  
  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}_${new Date().toISOString().split("T")[0]}.csv`);
  link.style.visibility = "hidden";
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function exportToPDF(
  transactions: Transaction[],
  wallets: Wallet[],
  metrics: {
    totalIncome: number;
    totalExpense: number;
    balance: number;
    period: string;
  }
): void {
  const printWindow = window.open("", "_blank");
  
  if (!printWindow) {
    alert("Please allow popups to export PDF");
    return;
  }
  
  const walletMap = new Map(wallets.map(w => [w.id, w.name]));
  
  const transactionsHTML = transactions.map(t => `
    <tr>
      <td>${t.date}</td>
      <td>${t.type === "income" ? "Pemasukan" : "Pengeluaran"}</td>
      <td>${t.category}</td>
      <td class="${t.type === "income" ? "income" : "expense"}">${formatCurrency(t.amount)}</td>
      <td>${walletMap.get(t.walletId || "") || "-"}</td>
      <td>${t.note || "-"}</td>
    </tr>
  `).join("");
  
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Laporan Keuangan - ${metrics.period}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { color: #333; border-bottom: 2px solid #6366F1; padding-bottom: 10px; }
        .summary { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin: 20px 0; }
        .summary-card { background: #f5f5f5; padding: 15px; border-radius: 8px; }
        .summary-card h3 { margin: 0; font-size: 12px; color: #666; }
        .summary-card p { margin: 5px 0 0; font-size: 18px; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 12px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background: #6366F1; color: white; }
        tr:nth-child(even) { background: #f9f9f9; }
        .income { color: #10B981; }
        .expense { color: #EF4444; }
        .footer { margin-top: 30px; font-size: 10px; color: #999; text-align: center; }
      </style>
    </head>
    <body>
      <h1>Laporan Keuangan</h1>
      <p><strong>Periode:</strong> ${metrics.period}</p>
      <p><strong>Tanggal Export:</strong> ${new Date().toLocaleDateString("id-ID")}</p>
      
      <div class="summary">
        <div class="summary-card">
          <h3>Total Pemasukan</h3>
          <p class="income">${formatCurrency(metrics.totalIncome)}</p>
        </div>
        <div class="summary-card">
          <h3>Total Pengeluaran</h3>
          <p class="expense">${formatCurrency(metrics.totalExpense)}</p>
        </div>
        <div class="summary-card">
          <h3>Saldo</h3>
          <p class="${metrics.balance >= 0 ? "income" : "expense"}">${formatCurrency(metrics.balance)}</p>
        </div>
      </div>
      
      <h2>Daftar Transaksi</h2>
      <table>
        <thead>
          <tr>
            <th>Tanggal</th>
            <th>Tipe</th>
            <th>Kategori</th>
            <th>Jumlah</th>
            <th>Dompet</th>
            <th>Catatan</th>
          </tr>
        </thead>
        <tbody>
          ${transactionsHTML}
        </tbody>
      </table>
      
      <div class="footer">
        Generated by FinTrack - Personal Finance Tracker
      </div>
      
      <script>
        window.onload = function() {
          setTimeout(function() {
            window.print();
          }, 500);
        };
      </script>
    </body>
    </html>
  `);
  
  printWindow.document.close();
}

export function exportBudgetReport(
  budgets: Budget[],
  period: string
): void {
  const printWindow = window.open("", "_blank");
  
  if (!printWindow) {
    alert("Please allow popups to export PDF");
    return;
  }
  
  const totalBudget = budgets.reduce((s, b) => s + b.limit, 0);
  const totalSpent = budgets.reduce((s, b) => s + b.spent, 0);
  
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Laporan Budget - ${period}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { color: #333; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background: #6366F1; color: white; }
        .over { color: #EF4444; }
        .safe { color: #10B981; }
      </style>
    </head>
    <body>
      <h1>Laporan Budget - ${period}</h1>
      <p><strong>Total Budget:</strong> ${formatCurrency(totalBudget)}</p>
      <p><strong>Total Terpakai:</strong> ${formatCurrency(totalSpent)}</p>
      
      <table>
        <thead>
          <tr>
            <th>Kategori</th>
            <th>Budget</th>
            <th>Terpakai</th>
            <th>Sisa</th>
            <th>%</th>
          </tr>
        </thead>
        <tbody>
          ${budgets.map(b => `
            <tr>
              <td>${b.category}</td>
              <td>${formatCurrency(b.limit)}</td>
              <td>${formatCurrency(b.spent)}</td>
              <td class="${b.spent > b.limit ? "over" : "safe"}">
                ${formatCurrency(b.limit - b.spent)}
              </td>
              <td>${Math.round((b.spent / b.limit) * 100)}%</td>
            </tr>
          `).join("")}
        </tbody>
      </table>
      
      <script>
        window.onload = function() {
          setTimeout(function() {
            window.print();
          }, 500);
        };
      </script>
    </body>
    </html>
  `);
  
  printWindow.document.close();
}

export function exportInvestmentReport(investments: Investment[]): void {
  const printWindow = window.open("", "_blank");
  
  if (!printWindow) {
    alert("Please allow popups to export PDF");
    return;
  }
  
  const totalInitial = investments.reduce((s, i) => s + i.initialValue, 0);
  const totalCurrent = investments.reduce((s, i) => s + i.currentValue, 0);
  const totalGain = totalCurrent - totalInitial;
  
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Laporan Investasi</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { color: #333; }
        .summary { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin: 20px 0; }
        .summary-card { background: #f5f5f5; padding: 15px; border-radius: 8px; }
        .gain { color: #10B981; }
        .loss { color: #EF4444; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background: #6366F1; color: white; }
      </style>
    </head>
    <body>
      <h1>Laporan Portofolio Investasi</h1>
      <p><strong>Tanggal:</strong> ${new Date().toLocaleDateString("id-ID")}</p>
      
      <div class="summary">
        <div class="summary-card">
          <h3>Total Investasi</h3>
          <p>${formatCurrency(totalInitial)}</p>
        </div>
        <div class="summary-card">
          <h3>Nilai Saat Ini</h3>
          <p>${formatCurrency(totalCurrent)}</p>
        </div>
        <div class="summary-card">
          <h3>Total Gain/Loss</h3>
          <p class="${totalGain >= 0 ? "gain" : "loss"}">
            ${totalGain >= 0 ? "+" : ""}${formatCurrency(totalGain)}
          </p>
        </div>
      </div>
      
      <table>
        <thead>
          <tr>
            <th>Nama</th>
            <th>Jenis</th>
            <th>Nilai Awal</th>
            <th>Nilai Saat Ini</th>
            <th>Gain/Loss</th>
          </tr>
        </thead>
        <tbody>
          ${investments.map(i => `
            <tr>
              <td>${i.name}</td>
              <td>${i.type}</td>
              <td>${formatCurrency(i.initialValue)}</td>
              <td>${formatCurrency(i.currentValue)}</td>
              <td class="${i.currentValue >= i.initialValue ? "gain" : "loss"}">
                ${formatCurrency(i.currentValue - i.initialValue)}
              </td>
            </tr>
          `).join("")}
        </tbody>
      </table>
      
      <script>
        window.onload = function() {
          setTimeout(function() {
            window.print();
          }, 500);
        };
      </script>
    </body>
    </html>
  `);
  
  printWindow.document.close();
}
